chore(deps): Bump lycheeverse/lychee-action from 2.0.2 to 2.6.1 (#286)
Bumps
[lycheeverse/lychee-action](https://github.com/lycheeverse/lychee-action)
from 2.0.2 to 2.6.1.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/lycheeverse/lychee-action/releases">lycheeverse/lychee-action's
releases</a>.</em></p>
<blockquote>
<h2>Version 2.6.1</h2>
<h2>What's Changed</h2>
<ul>
<li>Update lycheeVersion to v0.20.1 by <a
href="https://github.com/github-actions"><code>@​github-actions</code></a>[bot]
in <a
href="https://redirect.github.com/lycheeverse/lychee-action/pull/306">lycheeverse/lychee-action#306</a>,
which contains a hotfix for <a
href="https://redirect.github.com/lycheeverse/lychee-action/issues/305">lycheeverse/lychee-action#305</a>.</li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/lycheeverse/lychee-action/compare/v2...v2.6.1">https://github.com/lycheeverse/lychee-action/compare/v2...v2.6.1</a></p>
<h2>Version 2.6.0</h2>
<h2>What's Changed</h2>
<ul>
<li>Update lychee version to v0.20.0 by <a
href="https://github.com/github-actions"><code>@​github-actions</code></a>[bot]
in <a
href="https://redirect.github.com/lycheeverse/lychee-action/pull/304">lycheeverse/lychee-action#304</a></li>
<li>Bump actions/checkout from 4 to 5 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/lycheeverse/lychee-action/pull/303">lycheeverse/lychee-action#303</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/lycheeverse/lychee-action/compare/v2...v2.6.0">https://github.com/lycheeverse/lychee-action/compare/v2...v2.6.0</a></p>
<h2>Version 2.5.0</h2>
<h2>Summary</h2>
<p>Most notably with this release the deprecated
<code>--exclude-mail</code> flag was removed and the behavior of the
<code>--accept</code> flag was updated. Previously, status codes such as
200 OK were always accepted. Now they are only accepted by default. This
means providing the argument <code>--accept 201</code> now rejects
status code 200 OK.</p>
<h2>What's Changed</h2>
<ul>
<li>Update lycheeVersion to v0.19.1 by <a
href="https://github.com/github-actions"><code>@​github-actions</code></a>[bot]
in <a
href="https://redirect.github.com/lycheeverse/lychee-action/pull/300">lycheeverse/lychee-action#300</a></li>
<li>See the lychee changes here: <a
href="https://github.com/lycheeverse/lychee/releases/tag/lychee-v0.19.1">https://github.com/lycheeverse/lychee/releases/tag/lychee-v0.19.1</a>,
<a
href="https://github.com/lycheeverse/lychee/releases/tag/lychee-v0.19.0">https://github.com/lycheeverse/lychee/releases/tag/lychee-v0.19.0</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/lycheeverse/lychee-action/compare/v2...v2.5.0">https://github.com/lycheeverse/lychee-action/compare/v2...v2.5.0</a></p>
<h2>Version 2.4.1</h2>
<h2>What's Changed</h2>
<ul>
<li>Added Update Default Lychee version workflow by <a
href="https://github.com/Arteiii"><code>@​Arteiii</code></a> in <a
href="https://redirect.github.com/lycheeverse/lychee-action/pull/284">lycheeverse/lychee-action#284</a></li>
<li>Use temporary directory for lychee installation by <a
href="https://github.com/mre"><code>@​mre</code></a> in <a
href="https://redirect.github.com/lycheeverse/lychee-action/pull/287">lycheeverse/lychee-action#287</a></li>
<li>Fix <code>lychee</code> version check by <a
href="https://github.com/mondeja"><code>@​mondeja</code></a> in <a
href="https://redirect.github.com/lycheeverse/lychee-action/pull/288">lycheeverse/lychee-action#288</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/lycheeverse/lychee-action/compare/v2...v2.4.1">https://github.com/lycheeverse/lychee-action/compare/v2...v2.4.1</a></p>
<h2>Version 2.4.0</h2>
<h2>What's Changed</h2>
<ul>
<li>
<p>lychee now has a new task output, which allows to track which links
got fixed more easily.
It looks like this:</p>
<p>[test.html]:</p>
<ul>
<li><input type="checkbox" checked="" disabled="" /> [404] <a
href="https://en.wikipedia.org/wiki/foo">https://en.wikipedia.org/wiki/foo</a>
| Network error: Not Found</li>
<li><input type="checkbox" disabled="" /> [404] <a
href="https://en.wikipedia.org/wiki/bar">https://en.wikipedia.org/wiki/bar</a>
| Network error: Not Found</li>
<li><input type="checkbox" disabled="" /> [ERROR] <a
href="https://example.com/baz">https://example.com/baz</a> | Network
error: error sending request for url (<a
href="https://example.com/baz">https://example.com/baz</a>) Maybe a
certificate error?</li>
</ul>
<p>Each broken link has a checkbox that can be ticked off once fixed.
Credit goes to <a
href="https://github.com/Arteiii"><code>@​Arteiii</code></a> for the
idea and the implementation.
See <a
href="https://redirect.github.com/lycheeverse/lychee-action/issues/274">#274</a>
for more information.</p>
</li>
<li>
<p>Update To latest lychee Release by <a
href="https://github.com/Arteiii"><code>@​Arteiii</code></a> in <a
href="https://redirect.github.com/lycheeverse/lychee-action/pull/279">lycheeverse/lychee-action#279</a></p>
</li>
<li>
<p>Add <code>workingDirectory</code> argument by <a
href="https://github.com/mre"><code>@​mre</code></a> in <a
href="https://redirect.github.com/lycheeverse/lychee-action/pull/283">lycheeverse/lychee-action#283</a></p>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/lycheeverse/lychee-action/commit/885c65f3dc543b57c898c8099f4e08c8afd178a2"><code>885c65f</code></a>
[create-pull-request] automated change (<a
href="https://redirect.github.com/lycheeverse/lychee-action/issues/306">#306</a>)</li>
<li><a
href="https://github.com/lycheeverse/lychee-action/commit/01a5c94d8e012550040658854b90a7a7301e75ca"><code>01a5c94</code></a>
Update lycheeVersion to v0.20.0 (<a
href="https://redirect.github.com/lycheeverse/lychee-action/issues/304">#304</a>)</li>
<li><a
href="https://github.com/lycheeverse/lychee-action/commit/147829136ad8e72b5a1e57d782626a0ebd8d1d16"><code>1478291</code></a>
Bump actions/checkout from 4 to 5 (<a
href="https://redirect.github.com/lycheeverse/lychee-action/issues/303">#303</a>)</li>
<li><a
href="https://github.com/lycheeverse/lychee-action/commit/0c3ab057b2b5547f06cdb168502f7a2c7491497f"><code>0c3ab05</code></a>
Remove deprecrated flag <code>--exclude-mail</code></li>
<li><a
href="https://github.com/lycheeverse/lychee-action/commit/5c4ee84814c983aa7164eaee476f014e53ff3963"><code>5c4ee84</code></a>
[create-pull-request] automated change (<a
href="https://redirect.github.com/lycheeverse/lychee-action/issues/300">#300</a>)</li>
<li><a
href="https://github.com/lycheeverse/lychee-action/commit/74c50ae9cb26a12ef66ad5769546fe0848ae9596"><code>74c50ae</code></a>
[create-pull-request] automated change (<a
href="https://redirect.github.com/lycheeverse/lychee-action/issues/296">#296</a>)</li>
<li><a
href="https://github.com/lycheeverse/lychee-action/commit/82202e5e9c2f4ef1a55a3d02563e1cb6041e5332"><code>82202e5</code></a>
Fix <code>lychee</code> version check (<a
href="https://redirect.github.com/lycheeverse/lychee-action/issues/288">#288</a>)</li>
<li><a
href="https://github.com/lycheeverse/lychee-action/commit/52af76804efff53255d57c41fdfed5ea69b87927"><code>52af768</code></a>
Use temporary directory for lychee installation (<a
href="https://redirect.github.com/lycheeverse/lychee-action/issues/287">#287</a>)</li>
<li><a
href="https://github.com/lycheeverse/lychee-action/commit/6f793a7135344461673eecb342c75f3f110f5ebd"><code>6f793a7</code></a>
Added Update Default Lychee version workflow (<a
href="https://redirect.github.com/lycheeverse/lychee-action/issues/284">#284</a>)</li>
<li><a
href="https://github.com/lycheeverse/lychee-action/commit/1d97d84f0bc547f7b25f4c2170d87d810dc2fb2c"><code>1d97d84</code></a>
Add <code>workingDirectory</code> argument (<a
href="https://redirect.github.com/lycheeverse/lychee-action/issues/283">#283</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/lycheeverse/lychee-action/compare/v2.0.2...v2.6.1">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=lycheeverse/lychee-action&package-manager=github_actions&previous-version=2.0.2&new-version=2.6.1)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Idriss <44480885+m-idriss@users.noreply.github.com>